import type { Company } from "@/lib/types";

export const mockCompanies: Company[] = [
  {
    id: "cmp_001",
    name: "OpenAI",
    domain: "openai.com",
    tagline: "Frontier AI models and developer platform",
    description:
      "OpenAI develops and deploys foundation models and products used by consumers, developers, and enterprises worldwide.",
    stage: "Growth",
    sector: "AI/ML",
    tags: ["LLM", "Foundation Models", "API", "Research"],
    location: "San Francisco, CA",
    foundedYear: 2015,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$10B+",
    lastFundingDate: "2025-10-02",
    thesisScore: 97,
    thesisExplain: "Category-defining AI platform with deep enterprise pull-through",
    websiteUrl: "https://openai.com",
    linkedinUrl: "https://www.linkedin.com/company/openai",
    signals: [
      { id: "sig_001a", date: "2025-10-02", type: "funding", title: "Announced major strategic funding update" },
      { id: "sig_001b", date: "2025-12-12", type: "product", title: "Released new model capabilities" },
      { id: "sig_001c", date: "2026-01-18", type: "hiring", title: "Expanded hiring across research and safety" },
    ],
  },
  {
    id: "cmp_002",
    name: "Anthropic",
    domain: "anthropic.com",
    tagline: "Enterprise-grade AI assistants and model APIs",
    description:
      "Anthropic builds large language models and safety-focused AI products for developers and enterprises.",
    stage: "Growth",
    sector: "AI/ML",
    tags: ["LLM", "AI Safety", "Enterprise AI", "API"],
    location: "San Francisco, CA",
    foundedYear: 2021,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$8B+",
    lastFundingDate: "2025-09-11",
    thesisScore: 95,
    thesisExplain: "Strong model capability and enterprise adoption momentum",
    websiteUrl: "https://www.anthropic.com",
    linkedinUrl: "https://www.linkedin.com/company/anthropicresearch",
    signals: [
      { id: "sig_002a", date: "2025-09-11", type: "funding", title: "Expanded strategic capital commitments" },
      { id: "sig_002b", date: "2025-11-20", type: "product", title: "Launched model updates and developer tooling" },
      { id: "sig_002c", date: "2026-01-09", type: "partnership", title: "Deepened cloud and enterprise partnerships" },
    ],
  },
  {
    id: "cmp_003",
    name: "Databricks",
    domain: "databricks.com",
    tagline: "Unified data and AI platform",
    description:
      "Databricks provides analytics, machine learning, and data governance infrastructure for enterprise data teams.",
    stage: "Growth",
    sector: "AI/ML",
    tags: ["Data Platform", "ML", "Lakehouse", "Enterprise"],
    location: "San Francisco, CA",
    foundedYear: 2013,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$4B+",
    lastFundingDate: "2024-12-15",
    thesisScore: 92,
    thesisExplain: "Large enterprise footprint with durable platform economics",
    websiteUrl: "https://www.databricks.com",
    linkedinUrl: "https://www.linkedin.com/company/databricks",
    signals: [
      { id: "sig_003a", date: "2024-12-15", type: "funding", title: "Closed late-stage financing round" },
      { id: "sig_003b", date: "2025-07-30", type: "product", title: "Announced platform AI enhancements" },
      { id: "sig_003c", date: "2026-02-01", type: "partnership", title: "Expanded global cloud marketplace integrations" },
    ],
  },
  {
    id: "cmp_004",
    name: "Perplexity",
    domain: "perplexity.ai",
    tagline: "AI-native answer and research engine",
    description:
      "Perplexity delivers conversational search and citation-backed answers for professional and consumer use cases.",
    stage: "Series C+",
    sector: "AI/ML",
    tags: ["Search", "Consumer AI", "Research", "Productivity"],
    location: "San Francisco, CA",
    foundedYear: 2022,
    employeeCount: "51-200",
    revenue: "$5M-$10M ARR",
    fundingTotal: "$500M+",
    lastFundingDate: "2025-06-21",
    thesisScore: 90,
    thesisExplain: "Fast user growth with strong AI product differentiation",
    websiteUrl: "https://www.perplexity.ai",
    signals: [
      { id: "sig_004a", date: "2025-06-21", type: "funding", title: "Raised new growth financing" },
      { id: "sig_004b", date: "2025-10-18", type: "product", title: "Shipped new pro and team workflows" },
      { id: "sig_004c", date: "2026-01-12", type: "news", title: "Reported continued user growth milestones" },
    ],
  },
  {
    id: "cmp_005",
    name: "Hugging Face",
    domain: "huggingface.co",
    tagline: "Open-source AI model hub and tooling",
    description:
      "Hugging Face hosts model repositories, inference tooling, and collaboration workflows for the global ML community.",
    stage: "Series C+",
    sector: "Dev Tools",
    tags: ["Open Source", "ML", "Developer Platform", "Model Hub"],
    location: "New York, NY",
    foundedYear: 2016,
    employeeCount: "51-200",
    revenue: "$10M-$20M ARR",
    fundingTotal: "$300M+",
    lastFundingDate: "2025-03-10",
    thesisScore: 93,
    thesisExplain: "Developer network effects and strong open-source distribution",
    websiteUrl: "https://huggingface.co",
    githubUrl: "https://github.com/huggingface",
    signals: [
      { id: "sig_005a", date: "2025-03-10", type: "funding", title: "Completed strategic financing extension" },
      { id: "sig_005b", date: "2025-09-03", type: "product", title: "Rolled out enterprise model governance updates" },
      { id: "sig_005c", date: "2026-01-25", type: "partnership", title: "Expanded hardware and cloud ecosystem partnerships" },
    ],
  },
  {
    id: "cmp_006",
    name: "Uber",
    domain: "uber.com",
    tagline: "Global mobility and delivery marketplace",
    description:
      "Uber operates ride-hailing, delivery, and freight products connecting riders, drivers, couriers, and merchants.",
    stage: "Growth",
    sector: "Consumer",
    tags: ["Mobility", "Marketplace", "Delivery", "Logistics"],
    location: "San Francisco, CA",
    foundedYear: 2009,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$25B+",
    lastFundingDate: "2024-08-07",
    thesisScore: 80,
    thesisExplain: "Durable marketplace dynamics with scale advantages",
    websiteUrl: "https://www.uber.com",
    linkedinUrl: "https://www.linkedin.com/company/uber-com",
    signals: [
      { id: "sig_006a", date: "2024-08-07", type: "news", title: "Published quarterly mobility and delivery results" },
      { id: "sig_006b", date: "2025-04-15", type: "partnership", title: "Expanded mobility partnerships in key metros" },
      { id: "sig_006c", date: "2025-11-22", type: "product", title: "Rolled out new rider safety features" },
    ],
  },
  {
    id: "cmp_007",
    name: "Airbnb",
    domain: "airbnb.com",
    tagline: "Global platform for travel stays and experiences",
    description:
      "Airbnb powers marketplace transactions between hosts and travelers across homes, stays, and experiences.",
    stage: "Growth",
    sector: "Consumer",
    tags: ["Travel", "Marketplace", "Hospitality", "Consumer Internet"],
    location: "San Francisco, CA",
    foundedYear: 2008,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$6B+",
    lastFundingDate: "2024-11-07",
    thesisScore: 78,
    thesisExplain: "Strong network effects and global brand defensibility",
    websiteUrl: "https://www.airbnb.com",
    linkedinUrl: "https://www.linkedin.com/company/airbnb",
    signals: [
      { id: "sig_007a", date: "2024-11-07", type: "news", title: "Released earnings and product roadmap updates" },
      { id: "sig_007b", date: "2025-05-01", type: "product", title: "Launched host and guest trust improvements" },
      { id: "sig_007c", date: "2025-12-14", type: "partnership", title: "Expanded strategic partnerships in travel ecosystem" },
    ],
  },
  {
    id: "cmp_008",
    name: "DoorDash",
    domain: "doordash.com",
    tagline: "Local commerce and delivery infrastructure",
    description:
      "DoorDash enables food, grocery, and local retail delivery through logistics software and marketplace operations.",
    stage: "Growth",
    sector: "Consumer",
    tags: ["Delivery", "Local Commerce", "Marketplace", "Logistics"],
    location: "San Francisco, CA",
    foundedYear: 2013,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$2B+",
    lastFundingDate: "2024-10-30",
    thesisScore: 74,
    thesisExplain: "Strong execution in high-frequency logistics categories",
    websiteUrl: "https://www.doordash.com",
    linkedinUrl: "https://www.linkedin.com/company/doordash",
    signals: [
      { id: "sig_008a", date: "2024-10-30", type: "news", title: "Published quarterly local commerce performance" },
      { id: "sig_008b", date: "2025-06-20", type: "product", title: "Expanded merchant operations tooling" },
      { id: "sig_008c", date: "2026-01-19", type: "partnership", title: "Added new national retail partnerships" },
    ],
  },
  {
    id: "cmp_009",
    name: "Zomato",
    domain: "zomato.com",
    tagline: "Restaurant discovery and food delivery platform",
    description:
      "Zomato operates restaurant listings, food delivery, and digital commerce products across key consumer markets.",
    stage: "Growth",
    sector: "Consumer",
    tags: ["Food Delivery", "Marketplace", "Consumer Internet", "Logistics"],
    location: "Remote",
    foundedYear: 2008,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$2B+",
    lastFundingDate: "2024-08-01",
    thesisScore: 72,
    thesisExplain: "Scaled marketplace distribution with operational leverage",
    websiteUrl: "https://www.zomato.com",
    linkedinUrl: "https://www.linkedin.com/company/zomato",
    signals: [
      { id: "sig_009a", date: "2024-08-01", type: "news", title: "Published earnings update for core delivery business" },
      { id: "sig_009b", date: "2025-09-10", type: "partnership", title: "Expanded restaurant partnerships across new cities" },
      { id: "sig_009c", date: "2026-01-12", type: "product", title: "Introduced customer experience improvements in app" },
    ],
  },
  {
    id: "cmp_010",
    name: "Swiggy",
    domain: "swiggy.com",
    tagline: "Food delivery and quick commerce network",
    description:
      "Swiggy provides food and grocery fulfillment services with a wide courier, merchant, and consumer ecosystem.",
    stage: "Growth",
    sector: "Consumer",
    tags: ["Food Delivery", "Quick Commerce", "Marketplace", "Logistics"],
    location: "Remote",
    foundedYear: 2014,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$3B+",
    lastFundingDate: "2024-11-15",
    thesisScore: 71,
    thesisExplain: "Dense delivery operations with meaningful market penetration",
    websiteUrl: "https://www.swiggy.com",
    linkedinUrl: "https://www.linkedin.com/company/swiggy-in",
    signals: [
      { id: "sig_010a", date: "2024-11-15", type: "news", title: "Shared quick commerce and delivery growth update" },
      { id: "sig_010b", date: "2025-05-29", type: "product", title: "Shipped logistics and tracking improvements" },
      { id: "sig_010c", date: "2025-10-30", type: "partnership", title: "Expanded merchant partnerships for hyperlocal delivery" },
    ],
  },
  {
    id: "cmp_011",
    name: "Rapido",
    domain: "rapido.bike",
    tagline: "Bike taxi and last-mile mobility platform",
    description:
      "Rapido operates two-wheeler ride-hailing and last-mile mobility services optimized for dense urban commutes.",
    stage: "Series B",
    sector: "Consumer",
    tags: ["Mobility", "Ride Hailing", "Last Mile", "Two Wheeler"],
    location: "Remote",
    foundedYear: 2015,
    employeeCount: "51-200",
    revenue: "$5M-$10M ARR",
    fundingTotal: "$300M+",
    lastFundingDate: "2025-02-04",
    thesisScore: 68,
    thesisExplain: "Efficient logistics model in high-frequency commute corridors",
    websiteUrl: "https://www.rapido.bike",
    linkedinUrl: "https://www.linkedin.com/company/rapido-bike",
    signals: [
      { id: "sig_011a", date: "2025-02-04", type: "funding", title: "Closed new growth financing round" },
      { id: "sig_011b", date: "2025-08-08", type: "product", title: "Launched rider and captain app upgrades" },
      { id: "sig_011c", date: "2026-01-21", type: "partnership", title: "Expanded city-level transit partnerships" },
    ],
  },
  {
    id: "cmp_012",
    name: "Stripe",
    domain: "stripe.com",
    tagline: "Internet payments and financial infrastructure",
    description:
      "Stripe provides APIs and software to accept payments, manage billing, and run internet-native financial workflows.",
    stage: "Growth",
    sector: "FinTech",
    tags: ["Payments", "APIs", "Billing", "Financial Infrastructure"],
    location: "San Francisco, CA",
    foundedYear: 2010,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$9B+",
    lastFundingDate: "2025-03-18",
    thesisScore: 94,
    thesisExplain: "World-class developer-led distribution and infrastructure depth",
    websiteUrl: "https://stripe.com",
    linkedinUrl: "https://www.linkedin.com/company/stripe",
    signals: [
      { id: "sig_012a", date: "2025-03-18", type: "funding", title: "Expanded private financing commitments" },
      { id: "sig_012b", date: "2025-09-09", type: "product", title: "Released updates across billing and fraud stack" },
      { id: "sig_012c", date: "2026-01-07", type: "partnership", title: "Extended global acquiring partnerships" },
    ],
  },
  {
    id: "cmp_013",
    name: "Revolut",
    domain: "revolut.com",
    tagline: "Digital banking and global financial super app",
    description:
      "Revolut offers multi-currency banking, cards, investing, and business financial products in a digital-first platform.",
    stage: "Growth",
    sector: "FinTech",
    tags: ["Neobank", "Consumer Finance", "Cards", "International Payments"],
    location: "London, UK",
    foundedYear: 2015,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$1B+",
    lastFundingDate: "2024-12-12",
    thesisScore: 84,
    thesisExplain: "Scaled consumer finance distribution with strong product breadth",
    websiteUrl: "https://www.revolut.com",
    linkedinUrl: "https://www.linkedin.com/company/revolut",
    signals: [
      { id: "sig_013a", date: "2024-12-12", type: "news", title: "Published annual growth and profitability update" },
      { id: "sig_013b", date: "2025-07-16", type: "product", title: "Launched additional wealth and savings features" },
      { id: "sig_013c", date: "2025-12-20", type: "partnership", title: "Expanded card and payment network partnerships" },
    ],
  },
  {
    id: "cmp_014",
    name: "Plaid",
    domain: "plaid.com",
    tagline: "Data connectivity rails for financial applications",
    description:
      "Plaid connects consumer bank accounts to fintech applications through secure APIs and verification services.",
    stage: "Series C+",
    sector: "FinTech",
    tags: ["Open Banking", "APIs", "Verification", "Fintech Infrastructure"],
    location: "San Francisco, CA",
    foundedYear: 2013,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$1B+",
    lastFundingDate: "2025-05-12",
    thesisScore: 88,
    thesisExplain: "Critical data-infrastructure position in fintech value chain",
    websiteUrl: "https://plaid.com",
    linkedinUrl: "https://www.linkedin.com/company/plaid-",
    signals: [
      { id: "sig_014a", date: "2025-05-12", type: "news", title: "Announced expanded data network coverage" },
      { id: "sig_014b", date: "2025-10-11", type: "product", title: "Shipped risk and identity enhancements" },
      { id: "sig_014c", date: "2026-02-03", type: "partnership", title: "Added new core banking integrations" },
    ],
  },
  {
    id: "cmp_015",
    name: "Coinbase",
    domain: "coinbase.com",
    tagline: "Crypto exchange and onchain infrastructure",
    description:
      "Coinbase provides consumer and institutional crypto trading, custody, and developer infrastructure tools.",
    stage: "Growth",
    sector: "FinTech",
    tags: ["Crypto", "Exchange", "Custody", "Onchain"],
    location: "Remote",
    foundedYear: 2012,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$500M+",
    lastFundingDate: "2025-08-08",
    thesisScore: 73,
    thesisExplain: "Large brand and infrastructure position in onchain ecosystem",
    websiteUrl: "https://www.coinbase.com",
    linkedinUrl: "https://www.linkedin.com/company/coinbase",
    signals: [
      { id: "sig_015a", date: "2025-08-08", type: "news", title: "Published market and platform activity update" },
      { id: "sig_015b", date: "2025-11-14", type: "product", title: "Released developer tooling upgrades" },
      { id: "sig_015c", date: "2026-01-29", type: "partnership", title: "Expanded institutional service partnerships" },
    ],
  },
  {
    id: "cmp_016",
    name: "Vercel",
    domain: "vercel.com",
    tagline: "Frontend cloud and developer platform",
    description:
      "Vercel provides deployment, edge infrastructure, and workflow tooling for modern frontend and full-stack teams.",
    stage: "Series C+",
    sector: "Dev Tools",
    tags: ["Frontend", "Cloud", "Developer Platform", "Edge"],
    location: "San Francisco, CA",
    foundedYear: 2015,
    employeeCount: "51-200",
    revenue: "$10M-$20M ARR",
    fundingTotal: "$500M+",
    lastFundingDate: "2025-04-10",
    thesisScore: 92,
    thesisExplain: "Developer adoption flywheel with strong enterprise pull",
    websiteUrl: "https://vercel.com",
    githubUrl: "https://github.com/vercel",
    signals: [
      { id: "sig_016a", date: "2025-04-10", type: "news", title: "Shared growth across enterprise platform usage" },
      { id: "sig_016b", date: "2025-09-26", type: "product", title: "Announced platform and edge runtime enhancements" },
      { id: "sig_016c", date: "2026-02-04", type: "hiring", title: "Expanded hiring across developer success and platform teams" },
    ],
  },
  {
    id: "cmp_017",
    name: "Supabase",
    domain: "supabase.com",
    tagline: "Open-source backend platform for developers",
    description:
      "Supabase offers hosted Postgres, authentication, storage, and edge functions for building modern applications.",
    stage: "Series B",
    sector: "Dev Tools",
    tags: ["Open Source", "Database", "Backend", "Developer Platform"],
    location: "Remote",
    foundedYear: 2020,
    employeeCount: "51-200",
    revenue: "$5M-$10M ARR",
    fundingTotal: "$200M+",
    lastFundingDate: "2025-05-29",
    thesisScore: 91,
    thesisExplain: "OSS-led growth with durable developer ecosystem traction",
    websiteUrl: "https://supabase.com",
    githubUrl: "https://github.com/supabase",
    signals: [
      { id: "sig_017a", date: "2025-05-29", type: "funding", title: "Raised new growth financing" },
      { id: "sig_017b", date: "2025-10-07", type: "product", title: "Released platform and observability improvements" },
      { id: "sig_017c", date: "2026-01-15", type: "hiring", title: "Scaled developer relations and engineering teams" },
    ],
  },
  {
    id: "cmp_018",
    name: "GitLab",
    domain: "gitlab.com",
    tagline: "End-to-end DevSecOps platform",
    description:
      "GitLab provides source control, CI/CD, security scanning, and software delivery workflows in a unified platform.",
    stage: "Growth",
    sector: "Dev Tools",
    tags: ["DevSecOps", "CI/CD", "Source Control", "Enterprise"],
    location: "Remote",
    foundedYear: 2011,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$400M+",
    lastFundingDate: "2025-03-04",
    thesisScore: 86,
    thesisExplain: "Comprehensive platform strategy with strong enterprise usage",
    websiteUrl: "https://about.gitlab.com",
    linkedinUrl: "https://www.linkedin.com/company/gitlab-com",
    signals: [
      { id: "sig_018a", date: "2025-03-04", type: "news", title: "Published quarterly growth and enterprise metrics" },
      { id: "sig_018b", date: "2025-08-19", type: "product", title: "Expanded AI-assisted software delivery capabilities" },
      { id: "sig_018c", date: "2026-02-02", type: "partnership", title: "Deepened cloud provider integrations" },
    ],
  },
  {
    id: "cmp_019",
    name: "Notion",
    domain: "notion.so",
    tagline: "Connected workspace for docs, projects, and knowledge",
    description:
      "Notion helps teams manage documents, tasks, wikis, and planning in a collaborative workspace.",
    stage: "Series C+",
    sector: "SaaS",
    tags: ["Productivity", "Collaboration", "Knowledge Base", "Workspace"],
    location: "San Francisco, CA",
    foundedYear: 2013,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$300M+",
    lastFundingDate: "2024-09-20",
    thesisScore: 82,
    thesisExplain: "Strong product-led growth and high engagement footprint",
    websiteUrl: "https://www.notion.so",
    linkedinUrl: "https://www.linkedin.com/company/notionhq",
    signals: [
      { id: "sig_019a", date: "2024-09-20", type: "news", title: "Shared continued growth in enterprise usage" },
      { id: "sig_019b", date: "2025-07-11", type: "product", title: "Shipped AI and workflow automation updates" },
      { id: "sig_019c", date: "2025-12-03", type: "partnership", title: "Expanded productivity ecosystem integrations" },
    ],
  },
  {
    id: "cmp_020",
    name: "Figma",
    domain: "figma.com",
    tagline: "Collaborative design and product development platform",
    description:
      "Figma provides design, prototyping, and product collaboration tooling used by teams across software organizations.",
    stage: "Growth",
    sector: "SaaS",
    tags: ["Design", "Collaboration", "Product Development", "Enterprise"],
    location: "San Francisco, CA",
    foundedYear: 2012,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$700M+",
    lastFundingDate: "2025-01-25",
    thesisScore: 85,
    thesisExplain: "Category leadership with durable team-level adoption",
    websiteUrl: "https://www.figma.com",
    linkedinUrl: "https://www.linkedin.com/company/figma",
    signals: [
      { id: "sig_020a", date: "2025-01-25", type: "news", title: "Reported strong collaboration suite adoption" },
      { id: "sig_020b", date: "2025-10-02", type: "product", title: "Released product and developer collaboration features" },
      { id: "sig_020c", date: "2026-01-16", type: "hiring", title: "Scaled enterprise and platform engineering teams" },
    ],
  },
  {
    id: "cmp_021",
    name: "Canva",
    domain: "canva.com",
    tagline: "Visual design platform for teams and creators",
    description:
      "Canva enables individuals and organizations to design presentations, social assets, and brand content at scale.",
    stage: "Growth",
    sector: "SaaS",
    tags: ["Design", "Creator Tools", "Productivity", "Collaboration"],
    location: "Remote",
    foundedYear: 2013,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$600M+",
    lastFundingDate: "2025-06-01",
    thesisScore: 79,
    thesisExplain: "Large global distribution with broad product utility",
    websiteUrl: "https://www.canva.com",
    linkedinUrl: "https://www.linkedin.com/company/canva",
    signals: [
      { id: "sig_021a", date: "2025-06-01", type: "news", title: "Published growth update across enterprise adoption" },
      { id: "sig_021b", date: "2025-09-14", type: "product", title: "Released collaboration and AI design features" },
      { id: "sig_021c", date: "2026-02-06", type: "partnership", title: "Expanded integrations with workplace suites" },
    ],
  },
  {
    id: "cmp_022",
    name: "Cloudflare",
    domain: "cloudflare.com",
    tagline: "Connectivity cloud and internet security services",
    description:
      "Cloudflare provides network security, performance, and edge compute infrastructure for businesses globally.",
    stage: "Growth",
    sector: "Security",
    tags: ["Network Security", "Edge", "Zero Trust", "Infrastructure"],
    location: "San Francisco, CA",
    foundedYear: 2009,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$300M+",
    lastFundingDate: "2025-02-06",
    thesisScore: 88,
    thesisExplain: "Strong platform breadth across security and performance layers",
    websiteUrl: "https://www.cloudflare.com",
    linkedinUrl: "https://www.linkedin.com/company/cloudflare",
    signals: [
      { id: "sig_022a", date: "2025-02-06", type: "news", title: "Reported enterprise security growth metrics" },
      { id: "sig_022b", date: "2025-08-28", type: "product", title: "Expanded zero trust and application security features" },
      { id: "sig_022c", date: "2026-01-31", type: "partnership", title: "Deepened strategic cloud provider partnerships" },
    ],
  },
  {
    id: "cmp_023",
    name: "CrowdStrike",
    domain: "crowdstrike.com",
    tagline: "Cloud-native endpoint and identity security",
    description:
      "CrowdStrike delivers endpoint, cloud workload, and identity protection through its unified Falcon platform.",
    stage: "Growth",
    sector: "Security",
    tags: ["Endpoint Security", "Threat Intelligence", "Identity", "Enterprise"],
    location: "New York, NY",
    foundedYear: 2011,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$500M+",
    lastFundingDate: "2025-03-05",
    thesisScore: 83,
    thesisExplain: "Category strength in enterprise cybersecurity workloads",
    websiteUrl: "https://www.crowdstrike.com",
    linkedinUrl: "https://www.linkedin.com/company/crowdstrike",
    signals: [
      { id: "sig_023a", date: "2025-03-05", type: "news", title: "Published quarterly security platform growth" },
      { id: "sig_023b", date: "2025-09-24", type: "product", title: "Announced new threat detection capabilities" },
      { id: "sig_023c", date: "2026-01-20", type: "partnership", title: "Expanded alliances with major SIEM vendors" },
    ],
  },
  {
    id: "cmp_024",
    name: "Wiz",
    domain: "wiz.io",
    tagline: "Cloud security posture and risk management platform",
    description:
      "Wiz helps security teams discover and prioritize cloud risk across infrastructure, identities, and applications.",
    stage: "Series C+",
    sector: "Security",
    tags: ["Cloud Security", "CNAPP", "Risk", "Enterprise"],
    location: "New York, NY",
    foundedYear: 2020,
    employeeCount: "51-200",
    revenue: "$10M-$20M ARR",
    fundingTotal: "$1B+",
    lastFundingDate: "2025-05-20",
    thesisScore: 91,
    thesisExplain: "Exceptional enterprise velocity in high-priority security category",
    websiteUrl: "https://www.wiz.io",
    linkedinUrl: "https://www.linkedin.com/company/wizsecurity",
    signals: [
      { id: "sig_024a", date: "2025-05-20", type: "funding", title: "Closed large growth financing round" },
      { id: "sig_024b", date: "2025-10-09", type: "product", title: "Released new cloud risk remediation workflows" },
      { id: "sig_024c", date: "2026-02-02", type: "hiring", title: "Expanded enterprise go-to-market hiring" },
    ],
  },
  {
    id: "cmp_025",
    name: "Okta",
    domain: "okta.com",
    tagline: "Identity and access management for enterprises",
    description:
      "Okta provides authentication, authorization, and identity lifecycle management across workforce and customer apps.",
    stage: "Growth",
    sector: "Security",
    tags: ["Identity", "Access Management", "SSO", "Enterprise Security"],
    location: "San Francisco, CA",
    foundedYear: 2009,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$250M+",
    lastFundingDate: "2024-12-10",
    thesisScore: 76,
    thesisExplain: "Critical identity infrastructure with broad enterprise penetration",
    websiteUrl: "https://www.okta.com",
    linkedinUrl: "https://www.linkedin.com/company/okta-inc-",
    signals: [
      { id: "sig_025a", date: "2024-12-10", type: "news", title: "Shared quarterly identity platform metrics" },
      { id: "sig_025b", date: "2025-07-22", type: "product", title: "Rolled out adaptive identity security enhancements" },
      { id: "sig_025c", date: "2026-01-11", type: "partnership", title: "Expanded integration partnerships across SaaS ecosystem" },
    ],
  },
  {
    id: "cmp_026",
    name: "Tempus",
    domain: "tempus.com",
    tagline: "AI-driven precision medicine platform",
    description:
      "Tempus applies machine learning and clinical data infrastructure to support diagnostics and treatment decisions.",
    stage: "Series C+",
    sector: "HealthTech",
    tags: ["Precision Medicine", "Clinical Data", "AI", "Diagnostics"],
    location: "New York, NY",
    foundedYear: 2015,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$1B+",
    lastFundingDate: "2025-04-17",
    thesisScore: 75,
    thesisExplain: "Strong data moat and strategic healthcare distribution",
    websiteUrl: "https://www.tempus.com",
    linkedinUrl: "https://www.linkedin.com/company/tempus-ai",
    signals: [
      { id: "sig_026a", date: "2025-04-17", type: "news", title: "Published diagnostics and data network expansion update" },
      { id: "sig_026b", date: "2025-09-30", type: "product", title: "Launched new oncology decision support capabilities" },
      { id: "sig_026c", date: "2026-02-04", type: "partnership", title: "Expanded health system and biopharma collaborations" },
    ],
  },
  {
    id: "cmp_027",
    name: "Hims & Hers",
    domain: "hims.com",
    tagline: "Digital health and consumer telemedicine platform",
    description:
      "Hims & Hers provides telehealth services, digital care workflows, and consumer healthcare subscription products.",
    stage: "Growth",
    sector: "HealthTech",
    tags: ["Telehealth", "Consumer Health", "Subscriptions", "Digital Care"],
    location: "San Francisco, CA",
    foundedYear: 2017,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$300M+",
    lastFundingDate: "2025-03-12",
    thesisScore: 66,
    thesisExplain: "Strong brand and distribution with recurring digital care engagement",
    websiteUrl: "https://www.hims.com",
    linkedinUrl: "https://www.linkedin.com/company/forhims",
    signals: [
      { id: "sig_027a", date: "2025-03-12", type: "news", title: "Reported growth in subscription and telehealth services" },
      { id: "sig_027b", date: "2025-09-06", type: "product", title: "Expanded digital care programs across categories" },
      { id: "sig_027c", date: "2026-01-26", type: "partnership", title: "Added new pharmacy and provider network partnerships" },
    ],
  },
  {
    id: "cmp_028",
    name: "Oscar Health",
    domain: "hioscar.com",
    tagline: "Technology-enabled health insurance platform",
    description:
      "Oscar Health combines software and care navigation workflows to deliver digital-first health insurance experiences.",
    stage: "Growth",
    sector: "HealthTech",
    tags: ["Insurance", "Digital Health", "Care Navigation", "Platform"],
    location: "New York, NY",
    foundedYear: 2012,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$1B+",
    lastFundingDate: "2025-02-19",
    thesisScore: 62,
    thesisExplain: "Technology differentiation in large but competitive payer market",
    websiteUrl: "https://www.hioscar.com",
    linkedinUrl: "https://www.linkedin.com/company/oscar-health",
    signals: [
      { id: "sig_028a", date: "2025-02-19", type: "news", title: "Published performance update for digital insurance plans" },
      { id: "sig_028b", date: "2025-08-15", type: "product", title: "Shipped member-facing care experience updates" },
      { id: "sig_028c", date: "2026-01-30", type: "partnership", title: "Expanded provider and care delivery partnerships" },
    ],
  },
  {
    id: "cmp_029",
    name: "Climeworks",
    domain: "climeworks.com",
    tagline: "Direct air capture and carbon removal company",
    description:
      "Climeworks develops and operates direct air capture technology for permanent carbon dioxide removal.",
    stage: "Series C+",
    sector: "Climate",
    tags: ["Carbon Removal", "Direct Air Capture", "Climate Tech", "Infrastructure"],
    location: "London, UK",
    foundedYear: 2009,
    employeeCount: "51-200",
    revenue: "$5M-$10M ARR",
    fundingTotal: "$1B+",
    lastFundingDate: "2025-05-14",
    thesisScore: 70,
    thesisExplain: "Strong climate tailwinds with deep technical infrastructure moat",
    websiteUrl: "https://climeworks.com",
    linkedinUrl: "https://www.linkedin.com/company/climeworks",
    signals: [
      { id: "sig_029a", date: "2025-05-14", type: "funding", title: "Secured additional project and growth financing" },
      { id: "sig_029b", date: "2025-10-19", type: "partnership", title: "Expanded carbon removal offtake agreements" },
      { id: "sig_029c", date: "2026-01-27", type: "news", title: "Reported capacity expansion across capture facilities" },
    ],
  },
  {
    id: "cmp_030",
    name: "Rivian",
    domain: "rivian.com",
    tagline: "Electric vehicles and sustainable mobility",
    description:
      "Rivian designs and manufactures electric trucks, SUVs, and commercial delivery vehicles with integrated software.",
    stage: "Growth",
    sector: "Climate",
    tags: ["EV", "Mobility", "Sustainability", "Manufacturing"],
    location: "Remote",
    foundedYear: 2009,
    employeeCount: "200+",
    revenue: "$20M+ ARR",
    fundingTotal: "$10B+",
    lastFundingDate: "2025-07-09",
    thesisScore: 69,
    thesisExplain: "Strong climate category relevance with scale execution risk",
    websiteUrl: "https://rivian.com",
    linkedinUrl: "https://www.linkedin.com/company/rivian",
    signals: [
      { id: "sig_030a", date: "2025-07-09", type: "news", title: "Published production and delivery update" },
      { id: "sig_030b", date: "2025-11-01", type: "product", title: "Rolled out software and vehicle feature upgrades" },
      { id: "sig_030c", date: "2026-02-04", type: "partnership", title: "Expanded commercial fleet partnerships" },
    ],
  },
];
